export const studentQuotes = [
  "📖 Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",
  "🎯 Strive for progress, not perfection.",
  "🚀 The beautiful thing about learning is that no one can take it away from you.",
  "🌟 Success is the sum of small efforts, repeated day in and day out.",
  "📘 Learning is not attained by chance; it must be sought for with ardor and attended to with diligence.",
  "💡 Don’t watch the clock; do what it does. Keep going.",
  "🏆 Great things never come from comfort zones.",
  "🧠 The expert in anything was once a beginner.",
  "🔍 Mistakes are proof that you are trying.",
  "📅 Every day is a new opportunity to learn and grow.",
  "🛤️ The road to success is always under construction.",
  "📚 Study while others are sleeping. Succeed while others are wishing.",
  "🧗 Push yourself, because no one else is going to do it for you.",
  "🕰️ Time you enjoy wasting is not wasted time.",
  "🌈 Your education is a dress rehearsal for a life that is yours to lead.",
  "🔥 The future depends on what you do today.",
  "🌱 Small progress is still progress.",
  "🧩 The more that you learn, the more places you’ll go.",
  "🎓 Believe in yourself and all that you are.",
  "📖 Reading is to the mind what exercise is to the body.",
  "🌍 Be a student of life, not just of school.",
  "🎈 Don’t let what you cannot do interfere with what you can do.",
  "🚴‍♂️ Difficult roads often lead to beautiful destinations.",
  "🧪 Success is not just about talent, it's about consistent effort.",
  "🏁 Winners are not those who never fail, but those who never quit.",
  "🔬 Curiosity is the wick in the candle of learning.",
  "📐 Practice makes progress, not perfection.",
  "💭 Your only limit is your mind.",
  "🪴 Keep growing even if no one notices right away.",
  "🎤 Don’t be afraid to raise your hand and ask questions.",
  "🏋️ Learning is a treasure that will follow its owner everywhere.",
  "🚦 Start where you are. Use what you have. Do what you can.",
  "📊 Effort + Consistency = Success.",
  "📌 Focus on being productive instead of busy.",
  "🛎️ The secret of getting ahead is getting started.",
  "💼 Today’s accomplishments were yesterday’s impossibilities.",
  "📈 Every mistake is a step toward mastery.",
  "🎮 Level up your mind — read more, explore more.",
  "🔑 Discipline is the bridge between goals and achievement.",
  "🎨 Your brain is your canvas, keep painting knowledge.",
  "🎵 Success doesn't come to you — you go to it.",
  "🌅 Each morning we are born again. What we do today matters most.",
  "🧭 Don’t just study hard, study smart.",
  "🧳 Pack your day with purpose, not pressure.",
  "🌤️ Storms make trees take deeper roots — keep going.",
  "🎬 Don’t compare your Chapter 1 to someone else’s Chapter 20.",
  "🥇 You don’t have to be the best — just be better than yesterday.",
  "🌼 Bloom where you are planted.",
  "🗂️ Organize your mind, and your goals will follow.",
  "🧮 Dreams don’t work unless you do.",
  "🛸 Think beyond limits — imagination fuels success.",
];
